### ISSUE TITLE
logrotate with path testing

### ISSUE THREAD

**Issue by reelsense** [stationgroup/ansible-logrotate-plusplus#1]
## Description
I need a logrotate role that can test if paths exist before writing a logrotate config to the server. I want to load the roles default vars with custom paths and per path parameters, so I can run the playbook across a dynamic infrastructure and only write logerotate rules to the appropriate system with the correct paths present.

The ansible-galaxy role that was immediately intuitive to me was [weareinteractive/ansible-logrotate](https://github.com/weareinteractive/ansible-logrotate). If you find another role and you think that will do what I wan't let me know. Otherwise I need to modify an existing role.

## Example

Based on [weareinteractive/ansible-logrotate](https://github.com/weareinteractive/ansible-logrotate); Here is an example of what I imagine I would put in `defaults/main.yml`.

```yaml
 logrotate_scripts:
#   - name: nginx
#     path: /var/log/nginx/*.log
#     options:
#       - daily
#       - compress
#       - rotate 6
#       - missingok
#       - copytruncate
#       - delaycompress
#     scripts:
#       postrotate: "[ -s /run/nginx.pid ] && kill USR1 `cat /run/nginx.pid`"

   - name: 'nextcloud snap apache php_errors'
     path: /var/snap/nextcloud/current/apache/logs/*.log
     options:
       - daily
       - compress
       - rotate 6
       - missingok
       - copytruncate
       - delaycompress

   - name: nextcloud snap apache error_log
     path: /var/snap/nextcloud/current/apache/logs/error_log
     options:
       - daily
       - compress
       - rotate 6
       - missingok
       - copytruncate
       - delaycompress

   - name: custom
     path: /var/log/custom/*_log
     options:
       - daily
       - compress
       - rotate 6
```

If I'm remembering correctly, the last time I tried this with [weareinteractive/ansible-logrotate](https://github.com/weareinteractive/ansible-logrotate) I ended up creating nextcloud log rotation rules on systems that don't have those directories.

---

---
x-post: https://github.com/stationgroup/ansible-logrotate-plusplus/pull/2
